name: Check Weather

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: '3.11.4'
          cache: 'pip'
          check-latest: true
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run
        env:
          HOLIDAY_WEATHER_COLORFUL_CLOUDS: ${{ secrets.COLORFUL_CLOUDS }}
          HOLIDAY_WEATHER_SMTP: ${{ secrets.SMTP }}
        run: python3 main.py

      - name: Commit
        run: |
          git config --local user.email 393893729@qq.com
          git config --local user.name WangZhiYao
          git add .
          git commit -a -m "Update: `TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S'`"
          git push

